#!/usr/bin/env bash
set -e

## Create Repo metadata
createrepo_c -v /usr/share/nginx/html/errata5 \
 && createrepo_c -v /usr/share/nginx/html/errata6 \
 && createrepo_c -v /usr/share/nginx/html/errata7 \
 && createrepo_c -v /usr/share/nginx/html/errata8

## Get the errata file from CEFS, check the sha1sum and convert the file to compatible "yum repository" updateinfo.xml files
## Then we put the file in the repository
wget http://cefs.steve-meier.de/errata.latest.xml.bz2 \
 && wget -qO- http://cefs.steve-meier.de/errata.latest.sha1 | grep bz2 > check.sha1 && sha1sum -c check.sha1 \
 && bzip2 -dc errata.latest.xml.bz2 > errata.latest.xml \
 && ./generate_updateinfo.py -s all -t all -v -d ./ errata.latest.xml \
 && rm -rf errata.latest.xml* \								      \
 && mv /tmp/updateinfo-5/updateinfo.xml /usr/share/nginx/html/errata5/repodata/ \
 && mv /tmp/updateinfo-6/updateinfo.xml /usr/share/nginx/html/errata6/repodata/ \
 && mv /tmp/updateinfo-7/updateinfo.xml /usr/share/nginx/html/errata7/repodata/ \
 && mv /tmp/updateinfo-8/updateinfo.xml /usr/share/nginx/html/errata8/repodata/

## Tell the repository that it now contains errata
modifyrepo_c /usr/share/nginx/html/errata5/repodata/updateinfo.xml /usr/share/nginx/html/errata5/repodata \
 && modifyrepo_c /usr/share/nginx/html/errata6/repodata/updateinfo.xml /usr/share/nginx/html/errata6/repodata \
 && modifyrepo_c /usr/share/nginx/html/errata7/repodata/updateinfo.xml /usr/share/nginx/html/errata7/repodata \
 && modifyrepo_c /usr/share/nginx/html/errata8/repodata/updateinfo.xml /usr/share/nginx/html/errata8/repodata 

## Exit if no bucket is provided
## If you wish to run this container as the nginx server, you can comment everything below
echo "checking S3 Bucket" && \
  if [ -z "${S3_URI}" ]; \
  then \
    echo "missing ENV Variable : S3_URI" \
    && echo "you should provide the S3_URI in the form : S3_URI=s3://yourbucket/" \
    && exit 1; \
  fi

echo "retrieving config file from URI ${S3_URI}" \
    && aws s3 cp /usr/share/nginx/html ${S3_URI} --recursive

